packages:
    - www
allowBuilds:
    esbuild: true
    sharp: true
minimumReleaseAgeExclude:
    - "@biomejs/biome@2.5.0"
    - "@biomejs/cli-darwin-arm64@2.5.0"
    - "@biomejs/cli-darwin-x64@2.5.0"
    - "@biomejs/cli-linux-arm64-musl@2.5.0"
    - "@biomejs/cli-linux-arm64@2.5.0"
    - "@biomejs/cli-linux-x64-musl@2.5.0"
    - "@biomejs/cli-linux-x64@2.5.0"
    - "@biomejs/cli-win32-arm64@2.5.0"
    - "@biomejs/cli-win32-x64@2.5.0"
    - "@tailwindcss/node@4.3.1"
    - "@tailwindcss/oxide-android-arm64@4.3.1"
    - "@tailwindcss/oxide-darwin-arm64@4.3.1"
    - "@tailwindcss/oxide-darwin-x64@4.3.1"
    - "@tailwindcss/oxide-freebsd-x64@4.3.1"
    - "@tailwindcss/oxide-linux-arm-gnueabihf@4.3.1"
    - "@tailwindcss/oxide-linux-arm64-gnu@4.3.1"
    - "@tailwindcss/oxide-linux-arm64-musl@4.3.1"
    - "@tailwindcss/oxide-linux-x64-gnu@4.3.1"
    - "@tailwindcss/oxide-linux-x64-musl@4.3.1"
    - "@tailwindcss/oxide-wasm32-wasi@4.3.1"
    - "@tailwindcss/oxide-win32-arm64-msvc@4.3.1"
    - "@tailwindcss/oxide-win32-x64-msvc@4.3.1"
    - "@tailwindcss/oxide@4.3.1"
    - "@tailwindcss/vite@4.3.1"
    - tailwindcss@4.3.1
    - resend@6.14.0
onlyBuiltDependencies:
    - "@biomejs/biome"
    - "@tailwindcss/oxide"
    - esbuild
    - sharp
