import { envField } from "astro/config";

const coolifyEnv = {
	// Generated by Coolify
	COOLIFY_BRANCH: envField.string({ context: "client", access: "public", optional: true }),
	SOURCE_COMMIT: envField.string({ context: "client", access: "public", optional: true }),
};

const umamiEnv = {
	UMAMI_URL: envField.string({ context: "client", access: "public" }),
	UMAMI_SITE_ID: envField.string({ context: "client", access: "public" }),
	UMAMI_USERNAME: envField.string({ context: "server", access: "secret" }),
	UMAMI_PASSWORD: envField.string({ context: "server", access: "secret" }),
};

export default {
	SITE: envField.string({ context: "client", access: "public" }),
	OA_GITHUB_CLIENT_ID: envField.string({ context: "server", access: "secret" }),
	OA_GITHUB_CLIENT_SECRET: envField.string({ context: "server", access: "secret" }),
	OA_ALLOWED_DOMAINS: envField.string({ context: "server", access: "secret", optional: true }),
	GITHUB_API_AUTH_TOKEN: envField.string({ context: "server", access: "secret" }),
	HCAPTCHA_SITE_KEY: envField.string({ context: "client", access: "public" }),
	HCAPTCHA_SECRET_KEY: envField.string({ context: "server", access: "secret" }),
	RESEND_API_KEY: envField.string({ context: "server", access: "secret" }),
	CONTACT_FORM_ACCESS_KEY: envField.string({ context: "server", access: "public" }),
	PREVIEW: envField.boolean({ context: "client", access: "public", default: false }),
	UPTIME_API_TOKEN: envField.string({ context: "server", access: "secret" }),
	...umamiEnv,
	...coolifyEnv,
};
