// Generated by Wrangler on Mon Apr 01 2024 16:33:36 GMT+0200 (Central European Summer Time)
// by running `wrangler types ./src/worker-configuration.d.ts`

interface Env {
    CAISY_WEBHOOK_AUTH_KEY: string;
    CLOUDFLARE_PREVIEW_BUILD_HOOK_URL: string;
    CLOUDFLARE_PROD_BUILD_HOOK_URL: string;
    DISABLE_WEBHOOK_BUILD: string;
}
