#:schema node_modules/wrangler/config-schema.json
name = "cf-workers"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute