// Those types are incomplete and in most cases wrong.
// Generated by ChatGPT.

export interface TextNode {
    text: string;
    type: "text";
}

export interface LinkMark {
    type: "link";
    attrs: {
        class: string | null;
        href: string;
        target: string | null;
    };
}

export interface BoldMark {
    type: "bold";
}

export interface ItalicMark {
    type: "italic";
}

export interface CodeMark {
    type: "code";
}

export interface HardBreakNode {
    type: "hardBreak";
}

export interface HeadingNode {
    attrs: {
        level: number;
        textAlign: string;
    };
    content: TextNode[];
    type: "heading";
}

export interface ParagraphNode {
    attrs: {
        textAlign: string;
    };
    content: (TextNode | LinkMark | BoldMark | ItalicMark | CodeMark | HardBreakNode)[];
    type: "paragraph";
}

export interface BulletListNode {
    attrs: {
        textAlign: string;
    };
    content: ListItemNode[];
    type: "bulletList";
}

export interface ListItemNode {
    content: ParagraphNode[];
    type: "listItem";
}

export interface OrderedListNode {
    attrs: {
        start: number;
        textAlign: string;
    };
    content: ListItemNode[];
    type: "orderedList";
}

export interface TableRowNode {
    content: TableCellNode[];
    type: "tableRow";
}

export interface TableCellNode {
    attrs: {
        colspan: number;
        colwidth: null;
        rowspan: number;
        textAlign: string;
    };
    content: (ParagraphNode | HeadingNode)[];
    type: "tableCell";
}

export interface TableHeaderNode {
    attrs: {
        colspan: number;
        colwidth: null;
        rowspan: number;
        textAlign: string;
    };
    content: ParagraphNode[];
    type: "tableHeader";
}

export interface TableNode {
    content: (TableRowNode | TableHeaderNode)[];
    type: "table";
}

export interface BlockquoteNode {
    content: ParagraphNode[];
    type: "blockquote";
}

export interface IframeNode {
    attrs: {
        allow: null;
        allowfullscreen: null;
        frameborder: string;
        height: string;
        src: string;
        title: null;
        width: string;
    };
    type: "iframe";
}

export interface DocumentLinkNode {
    attrs: {
        documentId: string;
    };
    type: "documentLink";
}

export interface DocNode {
    content: (HeadingNode | ParagraphNode | BulletListNode | OrderedListNode | TableNode | BlockquoteNode | IframeNode | DocumentLinkNode)[];
    type: "doc";
}

export interface Connection {
    description: string;
    id: string;
    keywords: string;
    src: string;
    title: string;
}

export interface JSONData {
    connections: Connection[];
    json: DocNode;
}

// Source JSON for type generation.
/*
{
    "connections": [
        {
            "description": "",
            "id": "feabd8a0-0021-488c-bedc-3df6621da552",
            "keywords": "",
            "src": "https://assets.caisy.io/assets/5a686a80-4e1f-4737-ab1d-a831326bc98a/feabd8a0-0021-488c-bedc-3df6621da552/70beb827-1b57-4b25-840f-2b1cc7aaf7adqwickstartblueprintcreate.png",
            "title": "qwickstart_blueprint_create"
        }
    ],
    "json": {
        "content": [
            {
                "attrs": {
                    "level": 1,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 1",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "level": 2,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 2",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "level": 3,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 3",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "level": 4,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 4",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "level": 5,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 5",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "level": 6,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "heading 6",
                        "type": "text"
                    }
                ],
                "type": "heading"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "type": "hardBreak"
                    },
                    {
                        "text": "Something with ",
                        "type": "text"
                    },
                    {
                        "marks": [
                            {
                                "type": "bold"
                            }
                        ],
                        "text": "bold",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "Something with ",
                        "type": "text"
                    },
                    {
                        "marks": [
                            {
                                "type": "italic"
                            }
                        ],
                        "text": "italic",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "Something with ",
                        "type": "text"
                    },
                    {
                        "marks": [
                            {
                                "type": "code"
                            }
                        ],
                        "text": "code",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "Something left aligned",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "center"
                },
                "content": [
                    {
                        "text": "something centerd",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "right"
                },
                "content": [
                    {
                        "text": "Something right alrigned",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "justify"
                },
                "content": [
                    {
                        "text": " ",
                        "type": "text"
                    },
                    {
                        "type": "hardBreak"
                    },
                    {
                        "text": "Something stretched",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "content": [
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "text": "bullet list item 1",
                                        "type": "text"
                                    }
                                ],
                                "type": "paragraph"
                            }
                        ],
                        "type": "listItem"
                    },
                    {
                        "content": [
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "text": "bullet list item 2",
                                        "type": "text"
                                    }
                                ],
                                "type": "paragraph"
                            },
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "content": [
                                            {
                                                "attrs": {
                                                    "textAlign": "left"
                                                },
                                                "content": [
                                                    {
                                                        "text": "bullet list item 2-2",
                                                        "type": "text"
                                                    }
                                                ],
                                                "type": "paragraph"
                                            }
                                        ],
                                        "type": "listItem"
                                    },
                                    {
                                        "content": [
                                            {
                                                "attrs": {
                                                    "textAlign": "left"
                                                },
                                                "content": [
                                                    {
                                                        "text": "bullet list item with ",
                                                        "type": "text"
                                                    },
                                                    {
                                                        "marks": [
                                                            {
                                                                "type": "bold"
                                                            }
                                                        ],
                                                        "text": "bold mark",
                                                        "type": "text"
                                                    }
                                                ],
                                                "type": "paragraph"
                                            }
                                        ],
                                        "type": "listItem"
                                    }
                                ],
                                "type": "bulletList"
                            }
                        ],
                        "type": "listItem"
                    }
                ],
                "type": "bulletList"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "start": 1,
                    "textAlign": "left"
                },
                "content": [
                    {
                        "content": [
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "text": "order list item 1",
                                        "type": "text"
                                    }
                                ],
                                "type": "paragraph"
                            }
                        ],
                        "type": "listItem"
                    },
                    {
                        "content": [
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "text": "order list item 2",
                                        "type": "text"
                                    }
                                ],
                                "type": "paragraph"
                            },
                            {
                                "attrs": {
                                    "textAlign": "left"
                                },
                                "content": [
                                    {
                                        "content": [
                                            {
                                                "attrs": {
                                                    "textAlign": "left"
                                                },
                                                "content": [
                                                    {
                                                        "text": "order list item 2-2",
                                                        "type": "text"
                                                    }
                                                ],
                                                "type": "paragraph"
                                            }
                                        ],
                                        "type": "listItem"
                                    },
                                    {
                                        "content": [
                                            {
                                                "attrs": {
                                                    "textAlign": "left"
                                                },
                                                "content": [
                                                    {
                                                        "text": "order list item with ",
                                                        "type": "text"
                                                    },
                                                    {
                                                        "marks": [
                                                            {
                                                                "type": "bold"
                                                            }
                                                        ],
                                                        "text": "bold mark",
                                                        "type": "text"
                                                    }
                                                ],
                                                "type": "paragraph"
                                            }
                                        ],
                                        "type": "listItem"
                                    }
                                ],
                                "type": "bulletList"
                            }
                        ],
                        "type": "listItem"
                    }
                ],
                "type": "orderedList"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "content": [
                    {
                        "content": [
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "textAlign": "left"
                                        },
                                        "content": [
                                            {
                                                "text": "table header",
                                                "type": "text"
                                            }
                                        ],
                                        "type": "paragraph"
                                    }
                                ],
                                "type": "tableHeader"
                            },
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "textAlign": "left"
                                        },
                                        "content": [
                                            {
                                                "text": "table header 2",
                                                "type": "text"
                                            }
                                        ],
                                        "type": "paragraph"
                                    }
                                ],
                                "type": "tableHeader"
                            },
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "textAlign": "left"
                                        },
                                        "content": [
                                            {
                                                "text": "table header 3",
                                                "type": "text"
                                            }
                                        ],
                                        "type": "paragraph"
                                    }
                                ],
                                "type": "tableHeader"
                            }
                        ],
                        "type": "tableRow"
                    },
                    {
                        "content": [
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "textAlign": "left"
                                        },
                                        "content": [
                                            {
                                                "text": "item normal",
                                                "type": "text"
                                            }
                                        ],
                                        "type": "paragraph"
                                    }
                                ],
                                "type": "tableCell"
                            },
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "level": 2,
                                            "textAlign": "left"
                                        },
                                        "content": [
                                            {
                                                "text": "item headline 2",
                                                "type": "text"
                                            }
                                        ],
                                        "type": "heading"
                                    }
                                ],
                                "type": "tableCell"
                            },
                            {
                                "attrs": {
                                    "colspan": 1,
                                    "colwidth": null,
                                    "rowspan": 1
                                },
                                "content": [
                                    {
                                        "attrs": {
                                            "textAlign": "left"
                                        },
                                        "type": "paragraph"
                                    }
                                ],
                                "type": "tableCell"
                            }
                        ],
                        "type": "tableRow"
                    }
                ],
                "type": "table"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "some ",
                        "type": "text"
                    },
                    {
                        "marks": [
                            {
                                "attrs": {
                                    "class": null,
                                    "href": "https://caisy.io",
                                    "target": "_blank"
                                },
                                "type": "link"
                            }
                        ],
                        "text": "link ",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "allow": null,
                    "allowfullscreen": null,
                    "frameborder": "0",
                    "height": "100px",
                    "src": "https://www.youtube.com/embed/__mSgDEOyv8",
                    "title": null,
                    "width": "100px"
                },
                "type": "iframe"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": " asdfasdfasdf",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "content": [
                    {
                        "attrs": {
                            "textAlign": "left"
                        },
                        "content": [
                            {
                                "text": "Some quote",
                                "type": "text"
                            },
                            {
                                "type": "hardBreak"
                            }
                        ],
                        "type": "paragraph"
                    }
                ],
                "type": "blockquote"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "content": [
                    {
                        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum!",
                        "type": "text"
                    }
                ],
                "type": "paragraph"
            },
            {
                "attrs": {
                    "textAlign": "left"
                },
                "type": "paragraph"
            },
            {
                "attrs": {
                    "documentId": "feabd8a0-0021-488c-bedc-3df6621da552"
                },
                "type": "documentLink"
            }
        ],
        "type": "doc"
    }
}
*/
