// Generated by Wrangler on Sat Apr 13 2024 23:13:02 GMT+0200 (středoevropský letní čas)
// by running `wrangler types ./src/worker-configuration.d.ts`

interface Env {
	SANITY_WEBHOOK_AUTH_KEY: string;
	CLOUDFLARE_PREVIEW_BUILD_HOOK_URL: string;
	CLOUDFLARE_PROD_BUILD_HOOK_URL: string;
	DISABLE_WEBHOOK_BUILD: string;
}
