name: Delete preview on PR close

# only trigger on pull request closed events
on:
    pull_request:
        types: [closed]
        branches: [main]
permissions:
    pull-requests: write # GitHub Actions bot permissions

jobs:
    delete_preview:
        runs-on: ubuntu-latest
        env:
            PR_PATH: "${{ github.event.repository.name }}/${{ github.event.pull_request.number }}"
        steps:
            - name: Make empty dir
              run: mkdir dist

            - name: Save changes to preview repository
              uses: cpina/github-action-push-to-another-repository@v1.7.2
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "./dist/"
                  commit-message: "Deleted preview at ${{ PR_PATH }}"
                  destination-github-username: ${{ github.actor }}
                  destination-repository-name: "deploy-previews"
                  target-branch: main
                  target-directory: "${{ github.event.repository.name }}/${{ github.event.pull_request.number }}"

            - name: Comment on PR
              uses: hasura/comment-progress@v2.3.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  number: ${{ github.event.number }}
                  id: deploy-preview
                  message: "🪓 PR closed, deleted preview at https://dallyh.github.io/deploy-previews/${{ PR_PATH }}/"
