name: Delete preview on PR close

# only trigger on pull request closed events
on:
    pull_request:
        types: [closed]
        branches: [main]
    workflow_dispatch:

permissions:
    pull-requests: write # GitHub Actions bot permissions

jobs:
    delete_preview:
        runs-on: ubuntu-latest
        env:
            PR_PATH: ${{ github.event.repository.name }}/${{ github.event.pull_request.number }}
        steps:
            #    - name: Check if preview deploy is currently running and wait
            #      uses: lewagon/wait-on-check-action@v1.3.1
            #      with:
            #          ref: ${{ github.ref }}
            #          running-workflow-name: "Build and deploy new PR site preview"
            #          repo-token: ${{ secrets.GITHUB_TOKEN }}
            #          wait-interval: 10

            - name: Make empty dir
              run: mkdir dist

            - name: Save changes to preview repository
              uses: cpina/github-action-push-to-another-repository@v1.7.2
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "./dist/"
                  commit-message: "Deleted preview at ${{ env.PR_PATH }}"
                  destination-github-username: ${{ github.actor }}
                  destination-repository-name: "deploy-previews"
                  target-branch: main
                  target-directory: ${{ env.PR_PATH }}

            - name: Comment on PR
              uses: hasura/comment-progress@v2.3.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  number: ${{ github.event.number }}
                  id: deploy-preview
                  message: "🪓 PR closed, deleted preview at https://dallyh.github.io/deploy-previews/${{ env.PR_PATH }}/"
